module Website
  TITLE               = ENV['WEBSITE_TITLE']
  MAPS_KEY            = ENV['MAPS_KEY']
  AMIANDO_API_KEY     = ENV['AMIANDO_API_KEY']
  AMIANDO_EVENT_ID    = ENV['AMIANDO_EVENT_ID']
  GOOGLE_ANALYTICS_ID = ENV['GOOGLE_ANALYTICS_ID']
end
